[package]
name = "extpm"
version = "0.1.0"
authors = ["rsy3244 <r.sy3244@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
